In [30]:
# Import all libraries needed for the tutorial

# General syntax to import specific functions in a library: 
##from (library) import (specific library function)
from pandas import DataFrame, read_csv

# General syntax to import a library but no functions: 
##import (library) as (give the library a nickname/alias)
import matplotlib.pyplot as plt
import pandas as pd #this is how I usually import pandas
import sys #only needed to determine Python version number
import matplotlib #only needed to determine Matplotlib version number
import numpy as np

# Enable inline plotting
%matplotlib inline
print('Python version ' + sys.version)
print('Pandas version ' + pd.__version__)
print('Matplotlib version ' + matplotlib.__version__)

Python version 3.6.0 |Anaconda 4.3.1 (x86_64)| (default, Dec 23 2016, 13:19:00) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
Pandas version 0.19.2
Matplotlib version 2.0.0


In [40]:
Location = r'train.csv'
df = pd.read_csv(Location, parse_dates=['Date'])
print(type(df["Hour"][0]))

#testing Data
Location = r'test.csv'
test_df = pd.read_csv(Location, parse_dates=['Date'])
print(type(test_df["Hour"][0]))

sLength  = len(df['Hour'])
df['Day'] = pd.Series(sLength, index=df.index)
test_df['Day'] = pd.Series(sLength, index=df.index)

df.head()
#test_df.head()

<class 'str'>
<class 'str'>


Date         Hour  Excluded  Total  Flights  Booths  AvgWtTime   Day
0 2017-05-01  0000 - 0100        14    424        3      11         16  1135
1 2017-05-01  0200 - 0300         3    140        1       5          6  1135
2 2017-05-01  0600 - 0700         6    173        1      12         10  1135
3 2017-05-01  0700 - 0800        11    340        1      12         22  1135
4 2017-05-01  0800 - 0900        12    422        2      11         10  1135

In [41]:

#converting the 'Hour' column to Numbers for training
for i, row in df.iterrows():  #i: dataframe index; row: each row in series format
    df['Hour'][i] = int(df['Hour'][i][:2])
    df['Total'][i] = int(df['Total'][i] - df['Excluded'][i])
    df['Day'][i] = int(df['Date'][i].day)
#print(df.head())


#converting the 'Hour' column to Numbers for testing
for i, row in test_df.iterrows():  #i: dataframe index; row: each row in series format
    test_df['Hour'][i] = int(test_df['Hour'][i][:2])
    test_df['Total'][i] = int(test_df['Total'][i] - test_df['Excluded'][i])
    test_df['Day'][i] = int(test_df['Date'][i].day)

/Users/eabraham/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/eabraham/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/eabraham/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/eabraham/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:12: SettingWithCopyWarning: 
A value is trying to

In [95]:
#select columns here for features
flightDataPd = df[['Hour', 'Total','Booths','AvgWtTime']]
flightData = flightDataPd.as_matrix(columns=flightDataPd.columns[0:])
print(flightData)
#change the length of the features based on the selection
featureLength = 3
X = flightData[:,0:featureLength]
#print(data_X_train)
y = flightData[:,featureLength]
#print(data_y_train)
df.head()

[[0 410 11 16]
 [2 137 5 6]
 [6 167 12 10]
 ..., 
 [21 278 12 22]
 [22 167 12 11]
 [23 312 12 12]]


Date Hour  Excluded  Total  Flights  Booths  AvgWtTime  Day
0 2017-05-01    0        14    410        3      11         16    1
1 2017-05-01    2         3    137        1       5          6    1
2 2017-05-01    6         6    167        1      12         10    1
3 2017-05-01    7        11    329        1      12         22    1
4 2017-05-01    8        12    410        2      11         10    1

In [96]:
#select columns here for features
flightDataTestPd = test_df[['Hour','Total','Booths']]
flightDataTest = flightDataTestPd.as_matrix(columns=flightDataTestPd.columns[0:])

#change the length of the features based on the selection
data_X_testF = flightDataTest[:,0:featureLength]
#data_y_testF = flightDataTest[:,featureLength-1]
#print(data_y_test)
test_df.head()

Date Hour  Excluded  Total  Flights  Booths  Day
0 2017-07-01    0        14    300        2      12    1
1 2017-07-01    4         7    143        1       4    1
2 2017-07-01    6        12    411        2      13    1
3 2017-07-01    7        11    312        1      16    1
4 2017-07-01    8        17    427        2      14    1

In [105]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.cross_validation import cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures

data_X_train, data_X_test, data_y_train, data_y_test = train_test_split(X, y, test_size=0.3, random_state=42)


# Create linear regression object
regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(data_X_train, data_y_train)


# predict class labels for the test set
predicted = regr.predict(data_X_test)
#print(predicted)


# The mean squared error
print("Mean absolute error: %.2f"
      % mean_absolute_error(data_y_test, predicted))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % r2_score(data_y_test, predicted))


polynomial_features = PolynomialFeatures(degree=3, include_bias=False)

pipeline = Pipeline([("polynomial_features", polynomial_features),("linear_regression", regr)])
pipeline.fit(data_X_train, data_y_train)

    # Evaluate the models using crossvalidation
scores = cross_val_score(pipeline, data_X_train, data_y_train, scoring="neg_mean_squared_error", cv=10)
print(scores)

pred_deg = pipeline.predict(data_X_test)
#print(pred_deg)
#print(data_y_test)

# The mean squared error
print("Mean absolute error: %.2f"
      % mean_absolute_error(data_y_test, pred_deg))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % r2_score(data_y_test, pred_deg))

print(len(pred_deg))
print(len(data_y_test))
#print(metrics.accuracy_score(data_y_test, pred_deg))
#print(metrics.confusion_matrix(data_y_test, pred_deg))

Mean absolute error: 6.24
Variance score: 0.04
[-130.00060878 -106.55723364  -86.80633535  -67.38784096  -54.63602166
  -47.18775198  -50.80136408  -44.06329363  -50.85342643  -93.8926503 ]
Mean absolute error: 5.75
Variance score: 0.16
341
341


#### Final test for submission

In [104]:
pipeline.fit(X, y)

# Make predictions using the testing set
data_y_pred = pipeline.predict(data_X_testF)
df_y_pred = pd.DataFrame(data_y_pred)
prediction_location = r'prediction.csv'
df_y_pred.to_csv(prediction_location, index=False, header=['AvgWtTime'])
# The coefficients
print('Coefficients: \n', regr.coef_)
# The mean squared error
#print("Mean squared error: %.2f"
#      % mean_squared_error(data_y_test, data_y_pred))
# Explained variance score: 1 is perfect prediction
#print('Variance score: %.2f' % r2_score(data_y_test, data_y_pred))

Coefficients: 
 [  3.43380885e-01   2.45516923e-02   3.79813530e-01  -1.23896941e-02
  -7.71877753e-04   2.22030536e-03  -1.53331260e-06  -2.53100040e-04
  -9.07166441e-03]


In [ ]:
print(data_X_test.shape)
#print(data_y_test.shape)

In [36]:
index = 100
df['Day'][index] = int(df['Date'][index].day)
print(type(df['Day'][index]))

<class 'numpy.int64'>


/Users/eabraham/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app


In [64]:
flightDataTestPd.head(20)

Day Hour  Total  Flights  Booths
0     1    0    300        2      12
1     1    4    143        1       4
2     1    6    411        2      13
3     1    7    312        1      16
4     1    8    427        2      14
5     1    9    238        1      15
6     1   10    885        5      17
7     1   11    556        3      17
8     1   12    708        4      25
9     1   13   2469       11      33
10    1   14   2810       12      37
11    1   15   1829        8      27
12    1   16   1554        8      31
13    1   17   1384        9      30
14    1   18   2555       12      26
15    1   19   1021        5      21
16    1   20    410        2      11
17    1   21    259        1      10
18    1   23    471        3      10
19    2    0    321        2      10