In [30]:
# Import all libraries needed for the tutorial

# General syntax to import specific functions in a library: 
##from (library) import (specific library function)
from pandas import DataFrame, read_csv

# General syntax to import a library but no functions: 
##import (library) as (give the library a nickname/alias)
import matplotlib.pyplot as plt
import pandas as pd #this is how I usually import pandas
import sys #only needed to determine Python version number
import matplotlib #only needed to determine Matplotlib version number
import numpy as np

# Enable inline plotting
%matplotlib inline
print('Python version ' + sys.version)
print('Pandas version ' + pd.__version__)
print('Matplotlib version ' + matplotlib.__version__)

Python version 3.6.0 |Anaconda 4.3.1 (x86_64)| (default, Dec 23 2016, 13:19:00) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
Pandas version 0.19.2
Matplotlib version 2.0.0


In [40]:
Location = r'train.csv'
df = pd.read_csv(Location, parse_dates=['Date'])
print(type(df["Hour"][0]))

#testing Data
Location = r'test.csv'
test_df = pd.read_csv(Location, parse_dates=['Date'])
print(type(test_df["Hour"][0]))

sLength  = len(df['Hour'])
df['Day'] = pd.Series(sLength, index=df.index)
test_df['Day'] = pd.Series(sLength, index=df.index)

df.head()
#test_df.head()

<class 'str'>
<class 'str'>


Date         Hour  Excluded  Total  Flights  Booths  AvgWtTime   Day
0 2017-05-01  0000 - 0100        14    424        3      11         16  1135
1 2017-05-01  0200 - 0300         3    140        1       5          6  1135
2 2017-05-01  0600 - 0700         6    173        1      12         10  1135
3 2017-05-01  0700 - 0800        11    340        1      12         22  1135
4 2017-05-01  0800 - 0900        12    422        2      11         10  1135

In [41]:

#converting the 'Hour' column to Numbers for training
for i, row in df.iterrows():  #i: dataframe index; row: each row in series format
    df['Hour'][i] = int(df['Hour'][i][:2])
    df['Total'][i] = int(df['Total'][i] - df['Excluded'][i])
    df['Day'][i] = int(df['Date'][i].day)
#print(df.head())


#converting the 'Hour' column to Numbers for testing
for i, row in test_df.iterrows():  #i: dataframe index; row: each row in series format
    test_df['Hour'][i] = int(test_df['Hour'][i][:2])
    test_df['Total'][i] = int(test_df['Total'][i] - test_df['Excluded'][i])
    test_df['Day'][i] = int(test_df['Date'][i].day)

/Users/eabraham/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/eabraham/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/eabraham/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/eabraham/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:12: SettingWithCopyWarning: 
A value is trying to

In [42]:
#select columns here for features
flightDataPd = df[['Day','Hour', 'Total','Flights','Booths','AvgWtTime']]
flightData = flightDataPd.as_matrix(columns=flightDataPd.columns[0:])
print(flightData)
#change the length of the features based on the selection
featureLength = 5
data_X_train = flightData[:,0:featureLength]
print(data_X_train)
data_y_train = flightData[:,featureLength]
print(data_y_train)
df.head()

[[1 0 410 3 11 16]
 [1 2 137 1 5 6]
 [1 6 167 1 12 10]
 ..., 
 [30 21 278 1 12 22]
 [30 22 167 1 12 11]
 [30 23 312 2 12 12]]
[[1 0 410 3 11]
 [1 2 137 1 5]
 [1 6 167 1 12]
 ..., 
 [30 21 278 1 12]
 [30 22 167 1 12]
 [30 23 312 2 12]]
[16 6 10 ..., 22 11 12]


Date Hour  Excluded  Total  Flights  Booths  AvgWtTime  Day
0 2017-05-01    0        14    410        3      11         16    1
1 2017-05-01    2         3    137        1       5          6    1
2 2017-05-01    6         6    167        1      12         10    1
3 2017-05-01    7        11    329        1      12         22    1
4 2017-05-01    8        12    410        2      11         10    1

In [43]:
#select columns here for features
flightDataTestPd = test_df[['Day','Hour','Total','Flights','Booths']]
flightDataTest = flightDataTestPd.as_matrix(columns=flightDataTestPd.columns[0:])

#change the length of the features based on the selection
data_X_test = flightDataTest[:,0:featureLength]
#data_y_test = flightDataTest[:,featureLength-1]
#print(data_y_test)
test_df.head()

Date Hour  Excluded  Total  Flights  Booths  Day
0 2017-07-01    0        14    300        2      12    1
1 2017-07-01    4         7    143        1       4    1
2 2017-07-01    6        12    411        2      13    1
3 2017-07-01    7        11    312        1      16    1
4 2017-07-01    8        17    427        2      14    1

In [44]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split


#data_X_train, data_X_test, data_y_train, data_y_test = train_test_split(X, y, test_size=0, random_state=42)


# Create linear regression object
regr = linear_model.LinearRegression(normalize=True)

# Train the model using the training sets
regr.fit(data_X_train, data_y_train)

# Make predictions using the testing set
data_y_pred = regr.predict(data_X_test)
df_y_pred = pd.DataFrame(data_y_pred)
prediction_location = r'prediction.csv'
df_y_pred.to_csv(prediction_location, index=False, header=['AvgWtTime'])
# The coefficients
print('Coefficients: \n', regr.coef_)
# The mean squared error
#print("Mean squared error: %.2f"
#      % mean_squared_error(data_y_test, data_y_pred))
# Explained variance score: 1 is perfect prediction
#print('Variance score: %.2f' % r2_score(data_y_test, data_y_pred))



Coefficients: 
 [-0.05333598 -0.15352053  0.00870513 -1.13813118  0.03809152]


In [ ]:
print(data_X_test.shape)
#print(data_y_test.shape)

In [36]:
index = 100
df['Day'][index] = int(df['Date'][index].day)
print(type(df['Day'][index]))

<class 'numpy.int64'>


/Users/eabraham/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
