In [2]:
# Import all libraries needed for the tutorial

# General syntax to import specific functions in a library: 
##from (library) import (specific library function)
from pandas import DataFrame, read_csv

# General syntax to import a library but no functions: 
##import (library) as (give the library a nickname/alias)
import matplotlib.pyplot as plt
import pandas as pd #this is how I usually import pandas
import sys #only needed to determine Python version number
import matplotlib #only needed to determine Matplotlib version number
import numpy as np

# Enable inline plotting
%matplotlib inline
print('Python version ' + sys.version)
print('Pandas version ' + pd.__version__)
print('Matplotlib version ' + matplotlib.__version__)

Python version 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 13:19:00) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
Pandas version 0.21.1
Matplotlib version 2.0.2


In [44]:
Location = r'train.csv'
df = pd.read_csv(Location, parse_dates=['booking_date', 'dep_date'])
#pd.to_datetime(pd.Series(sLength, index=df.index))
#print(type(df["Hour"][0]))

#testing Data
Location = r'test.csv'
test_df = pd.read_csv(Location, parse_dates=['booking_date', 'dep_date'])
#print(type(test_df["Hour"][0]))

sLength  = len(df['pax'])
#df['dep_time'] = pd.to_datetime(pd.Series(sLength, index=df.index))
#test_df['Day'] = pd.Series(sLength, index=df.index)

originList = df.origin.unique()
df = df.assign(id=(df['origin'] + '_' + df['destination']).astype('category').cat.codes)
df['days'] = ((df['dep_date'] - df['booking_date'])/np.timedelta64(1, 'D')).astype(int)/365
df['fare_choice_sc'] = df.groupby(['fare_choice']).ngroup()
df['dep_time_sc'] = ((df['dep_time']%100).astype(int)/5 + (df['dep_time']/100).astype(int)*12)/(24*12)
#df['id2'] = df.groupby(['destination']).ngroup()


df.head(30)
#test_df.head()

#print(df.origin.unique())
#print(test_df.origin.unique())
#print(df.destination.unique())
#print(test_df.destination.unique())
#df.destination.unique()

id booking_date origin destination   dep_date  dep_time  pax fare_choice  \
0   14   2017-02-10    MAA         DEL 2017-06-01       630    2        Deal   
1    8   2017-05-27    DEL         BOM 2017-06-01      1745    1     Classic   
2    4   2017-05-30    BOM         DEL 2017-06-01       900    1       Saver   
3    2   2017-05-30    BOM         BLR 2017-06-01      2130    2     Classic   
4    8   2017-05-30    DEL         BOM 2017-06-01      1240    1     Classic   
5    8   2017-05-30    DEL         BOM 2017-06-01      1030    1        Flex   
6    7   2017-05-30    DEL         BLR 2017-06-01       705    3     Classic   
7    0   2017-05-31    BLR         BOM 2017-06-01       855    1     Classic   
8    4   2017-05-31    BOM         DEL 2017-06-01      2055    1     Classic   
9   14   2017-05-11    MAA         DEL 2017-06-01       630    2        Deal   
10   3   2017-06-01    BOM         CCU 2017-06-01      1255    1     Classic   
11   5   2017-06-01    BOM         MAA 2017-06-01      1915    2        Deal   
12  12   2017-04-28    HYD         BOM 2017-06-01      1940    1       Saver   
13  14   2017-03-26    MAA         DEL 2017-06-01       630    1       Saver   
14   7   2017-03-10    DEL         BLR 2017-06-01      1150    3       Saver   
15   3   2017-05-29    BOM         CCU 2017-06-01      1750    1     Classic   
16   7   2017-05-30    DEL         BLR 2017-06-01       705    1     Classic   
17   7   2017-05-30    DEL         BLR 2017-06-01       750    1     Classic   
18   8   2017-05-30    DEL         BOM 2017-06-01      2245    1     Classic   
19   7   2017-05-03    DEL         BLR 2017-06-01      2045    1       Saver   
20   4   2017-05-31    BOM         DEL 2017-06-01       700    1       Saver   
21   0   2017-05-24    BLR         BOM 2017-06-01      2150    1       Saver   
22   4   2017-05-31    BOM         DEL 2017-06-01       730    1     Classic   
23   8   2017-05-31    DEL         BOM 2017-06-01      2050    1        Flex   
24  11   2017-06-01    GOI         BOM 2017-06-01      1500    1     Classic   
25   0   2017-06-01    BLR         BOM 2017-06-01      2150    2     Classic   
26   4   2017-06-01    BOM         DEL 2017-06-01      1630    1       Saver   
27   8   2017-05-26    DEL         BOM 2017-06-01       945    1       Saver   
28   0   2017-05-26    BLR         BOM 2017-06-01      2035    4     Classic   
29  13   2017-05-26    MAA         BOM 2017-06-01       700    1     Classic   

        days  fare_choice_sc  dep_time_sc  
0   0.304110               1     0.270833  
1   0.013699               0     0.739583  
2   0.005479               3     0.375000  
3   0.005479               0     0.895833  
4   0.005479               0     0.527778  
5   0.005479               2     0.437500  
6   0.005479               0     0.295139  
7   0.002740               0     0.371528  
8   0.002740               0     0.871528  
9   0.057534               1     0.270833  
10  0.000000               0     0.538194  
11  0.000000               1     0.802083  
12  0.093151               3     0.819444  
13  0.183562               3     0.270833  
14  0.227397               3     0.493056  
15  0.008219               0     0.743056  
16  0.005479               0     0.295139  
17  0.005479               0     0.326389  
18  0.005479               0     0.947917  
19  0.079452               3     0.864583  
20  0.002740               3     0.291667  
21  0.021918               3     0.909722  
22  0.002740               0     0.312500  
23  0.002740               2     0.868056  
24  0.000000               0     0.625000  
25  0.000000               0     0.909722  
26  0.000000               3     0.687500  
27  0.016438               3     0.406250  
28  0.016438               0     0.857639  
29  0.016438               0     0.291667

In [14]:

#converting the 'Hour' column to Numbers for training
for i, row in df.iterrows():  #i: dataframe index; row: each row in series format
    df['dep_time'][i] = int(df['dep_time'][i][:2]) + 1
    #df['Total'][i] = int(df['Total'][i] - df['Excluded'][i])
    #df['Day'][i] = int(df['Date'][i].dayofweek) + 1
#print(df.head())


#converting the 'Hour' column to Numbers for testing
for i, row in test_df.iterrows():  #i: dataframe index; row: each row in series format
    test_df['Hour'][i] = int(test_df['Hour'][i][:2]) + 1
    #test_df['Total'][i] = int(test_df['Total'][i] - test_df['Excluded'][i])
    #test_df['Day'][i] = int(test_df['Date'][i].dayofweek) + 1

IndexError: invalid index to scalar variable.

In [151]:
#select columns here for features
flightDataPd = df[['Day','Hour', 'Total','Flights','Booths','AvgWtTime']]
flightData = flightDataPd.as_matrix(columns=flightDataPd.columns[0:])
print(flightData)
#change the length of the features based on the selection
featureLength = 5
X = flightData[:,0:featureLength]
#print(data_X_train)
y = flightData[:,featureLength]
#print(data_y_train)
df.head()

[[1 1 410 3 11 16]
 [1 3 137 1 5 6]
 [1 7 167 1 12 10]
 ..., 
 [5 22 278 1 12 22]
 [5 23 167 1 12 11]
 [5 24 312 2 12 12]]


Date Hour  Excluded  Total  Flights  Booths  AvgWtTime  Day
0 2017-05-01    1        14    410        3      11         16    1
1 2017-05-01    3         3    137        1       5          6    1
2 2017-05-01    7         6    167        1      12         10    1
3 2017-05-01    8        11    329        1      12         22    1
4 2017-05-01    9        12    410        2      11         10    1

In [152]:
#select columns here for features
flightDataTestPd = test_df[['Day','Hour','Total','Flights','Booths']]
flightDataTest = flightDataTestPd.as_matrix(columns=flightDataTestPd.columns[0:])

#change the length of the features based on the selection
data_X_testF = flightDataTest[:,0:featureLength]
#data_y_testF = flightDataTest[:,featureLength-1]
#print(data_y_test)
test_df.head()

Date Hour  Excluded  Total  Flights  Booths  Day
0 2017-07-01    1        14    300        2      12    6
1 2017-07-01    5         7    143        1       4    6
2 2017-07-01    7        12    411        2      13    6
3 2017-07-01    8        11    312        1      16    6
4 2017-07-01    9        17    427        2      14    6

In [153]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.cross_validation import cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures

data_X_train, data_X_test, data_y_train, data_y_test = train_test_split(X, y, test_size=0.3, random_state=42)


# Create linear regression object
regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(data_X_train, data_y_train)


# predict class labels for the test set
predicted = regr.predict(data_X_test)
#print(predicted)


# The mean squared error
print("Mean absolute error: %.2f"
      % mean_absolute_error(data_y_test, predicted))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % r2_score(data_y_test, predicted))


polynomial_features = PolynomialFeatures(degree=3, include_bias=False)

pipeline = Pipeline([("polynomial_features", polynomial_features),("linear_regression", regr)])
pipeline.fit(data_X_train, data_y_train)

    # Evaluate the models using crossvalidation
scores = cross_val_score(pipeline, data_X_train, data_y_train, scoring="neg_mean_squared_error", cv=10)
print(scores)

pred_deg = pipeline.predict(data_X_test)
#print(pred_deg)
#print(data_y_test)

# The mean squared error
print("Mean absolute error: %.2f"
      % mean_absolute_error(data_y_test, pred_deg))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % r2_score(data_y_test, pred_deg))

print(len(pred_deg))
print(len(data_y_test))
#print(metrics.accuracy_score(data_y_test, pred_deg))
#print(metrics.confusion_matrix(data_y_test, pred_deg))

Mean absolute error: 6.21
Variance score: 0.06
[-124.76711011  -90.51990651  -79.43858031  -69.41157216  -56.03881067
  -39.16540077  -43.02606604  -47.08598097  -44.41796257  -83.21007004]
Mean absolute error: 5.58
Variance score: 0.22
341
341


### Final test for submission

In [154]:
pipeline.fit(X, y)

# Make predictions using the testing set
data_y_pred = pipeline.predict(data_X_testF)
df_y_pred = pd.DataFrame(data_y_pred)
prediction_location = r'prediction.csv'
df_y_pred.to_csv(prediction_location, index=False, header=['AvgWtTime'])
prediction_location = r'train_mod.csv'
np.savetxt("train_mod.csv", flightData, delimiter=",")
# The coefficients
print('Coefficients: \n', regr.coef_)
# The mean squared error
#print("Mean squared error: %.2f"
#      % mean_squared_error(data_y_test, data_y_pred))
# Explained variance score: 1 is perfect prediction
#print('Variance score: %.2f' % r2_score(data_y_test, data_y_pred))

Coefficients: 
 [ -7.64530259e+00  -1.29502594e+00   2.14665581e-01  -2.91826937e+01
  -3.46828210e-01   2.22305555e+00  -4.83827052e-02  -5.44089625e-03
   1.66356177e+00   1.73914026e-02   9.69630244e-02  -1.32595301e-02
   1.72320568e+00   1.93442589e-01   3.84552808e-04  -1.44564484e-01
  -9.20029442e-03   1.33276125e+01   1.34698060e+00  -3.23458632e-02
  -1.83319994e-01  -1.83174282e-02  -6.44107336e-04   7.57756678e-02
   8.46564313e-03   9.36540718e-03   2.36708747e-04  -5.08547557e-02
  -6.61870677e-03  -8.42549411e-06   3.60231759e-03   1.67912415e-04
  -3.72282061e-01  -4.59669943e-02   2.93164663e-03  -1.93596081e-03
   1.96755893e-04  -2.25508813e-02  -8.22450170e-03  -1.14503013e-05
   3.97763056e-03   4.20073522e-04  -3.35132874e-01  -6.80967000e-02
   2.18342613e-03   1.14505587e-07  -7.29166959e-05  -4.13667626e-06
   1.53668232e-02   1.60319105e-03   3.90086178e-05  -1.06926744e+00
  -1.53161182e-01  -2.15356466e-03  -6.59889272e-04]


In [ ]:
print(data_X_test.shape)
#print(data_y_test.shape)

In [117]:
index = 138
df['Day'][index] = int(df['Date'][index].day)
print(type(df['Day'][index]))

print(type(df['Date'][index].dayofweek))

<class 'numpy.int64'>
<class 'int'>


/Users/eabraham/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app


In [64]:
flightDataTestPd.head(20)

Day Hour  Total  Flights  Booths
0     1    0    300        2      12
1     1    4    143        1       4
2     1    6    411        2      13
3     1    7    312        1      16
4     1    8    427        2      14
5     1    9    238        1      15
6     1   10    885        5      17
7     1   11    556        3      17
8     1   12    708        4      25
9     1   13   2469       11      33
10    1   14   2810       12      37
11    1   15   1829        8      27
12    1   16   1554        8      31
13    1   17   1384        9      30
14    1   18   2555       12      26
15    1   19   1021        5      21
16    1   20    410        2      11
17    1   21    259        1      10
18    1   23    471        3      10
19    2    0    321        2      10