In [37]:
# Import all libraries needed for the tutorial

# General syntax to import specific functions in a library: 
##from (library) import (specific library function)
from pandas import DataFrame, read_csv

# General syntax to import a library but no functions: 
##import (library) as (give the library a nickname/alias)
import matplotlib.pyplot as plt
import pandas as pd #this is how I usually import pandas
import sys #only needed to determine Python version number
import matplotlib #only needed to determine Matplotlib version number
import numpy as np

# Enable inline plotting
%matplotlib inline
print('Python version ' + sys.version)
print('Pandas version ' + pd.__version__)
print('Matplotlib version ' + matplotlib.__version__)  

Python version 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 13:19:00) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
Pandas version 0.21.1
Matplotlib version 2.0.2


In [38]:
Location = r'train.csv'
df = pd.read_csv(Location, parse_dates=['booking_date', 'dep_date'])
#pd.to_datetime(pd.Series(sLength, index=df.index))
#print(type(df["Hour"][0]))

#testing Data
Location = r'test.csv'
test_df = pd.read_csv(Location, parse_dates=['booking_date', 'dep_date'])
#print(type(test_df["Hour"][0]))

sLength  = len(df['pax'])
#df['dep_time'] = pd.to_datetime(pd.Series(sLength, index=df.index))
#test_df['Day'] = pd.Series(sLength, index=df.index)

originList = df.origin.unique()
df = df.assign(id=(df['origin'] + '_' + df['destination']).astype('category').cat.codes)
df['days'] = ((df['dep_date'] - df['booking_date'])/np.timedelta64(1, 'D')).astype(int)/365
df['fare_choice_sc'] = df.groupby(['fare_choice']).ngroup()
df['dep_time_sc'] = ((df['dep_time']%100).astype(int)/5 + (df['dep_time']/100).astype(int)*12)/(24*12)
#df['id2'] = df.groupby(['destination']).ngroup()
maxID  = max(df['id'])
df['id'] = df['id']/maxID
print(sLength)

sLength  = len(test_df['pax'])
test_df = test_df.assign(id=(test_df['origin'] + '_' + test_df['destination']).astype('category').cat.codes)
test_df['days'] = ((test_df['dep_date'] - test_df['booking_date'])/np.timedelta64(1, 'D')).astype(int)/365
test_df['dep_time_sc'] = ((test_df['dep_time']%100).astype(int)/5 + (test_df['dep_time']/100).astype(int)*12)/(24*12)
#df['id2'] = df.groupby(['destination']).ngroup()
maxID  = max(test_df['id'])
test_df['id'] = test_df['id']/maxID
print(sLength)

df.head(5)
test_df.head()

#print(df.origin.unique())
#print(test_df.origin.unique())
#print(df.destination.unique())
#print(test_df.destination.unique())
#df.destination.unique()

73830
22830


id booking_date origin destination   dep_date  dep_time  pax  \
0  0.071429   2017-04-21    BLR         DEL 2017-06-24      1745    2   
1  0.285714   2017-05-24    BOM         DEL 2017-06-24      1700    2   
2  0.071429   2017-04-12    BLR         DEL 2017-06-24       700    1   
3  0.071429   2017-06-21    BLR         DEL 2017-06-24      1125    2   
4  0.214286   2017-05-31    BOM         CCU 2017-06-24      1905    1   

       days  dep_time_sc  
0  0.175342     0.739583  
1  0.084932     0.708333  
2  0.200000     0.291667  
3  0.008219     0.475694  
4  0.065753     0.795139

In [39]:
#select columns here for features
flightDataPd = df[['id','pax', 'days','dep_time_sc','fare_choice_sc']]
flightData = flightDataPd.as_matrix(columns=flightDataPd.columns[0:])
print(flightData)
#change the length of the features based on the selection
featureLength = 4
X = flightData[:,0:featureLength]
print(X)
y = flightData[:,featureLength]
print(y)
df.head()

[[ 1.          2.          0.30410959  0.27083333  1.        ]
 [ 0.57142857  1.          0.01369863  0.73958333  0.        ]
 [ 0.28571429  1.          0.00547945  0.375       3.        ]
 ..., 
 [ 0.57142857  3.          0.10410959  0.40625     1.        ]
 [ 0.42857143  1.          0.06575342  0.58680556  1.        ]
 [ 0.35714286  1.          0.00821918  0.35763889  0.        ]]
[[ 1.          2.          0.30410959  0.27083333]
 [ 0.57142857  1.          0.01369863  0.73958333]
 [ 0.28571429  1.          0.00547945  0.375     ]
 ..., 
 [ 0.57142857  3.          0.10410959  0.40625   ]
 [ 0.42857143  1.          0.06575342  0.58680556]
 [ 0.35714286  1.          0.00821918  0.35763889]]
[ 1.  0.  3. ...,  1.  1.  0.]


id booking_date origin destination   dep_date  dep_time  pax  \
0  1.000000   2017-02-10    MAA         DEL 2017-06-01       630    2   
1  0.571429   2017-05-27    DEL         BOM 2017-06-01      1745    1   
2  0.285714   2017-05-30    BOM         DEL 2017-06-01       900    1   
3  0.142857   2017-05-30    BOM         BLR 2017-06-01      2130    2   
4  0.571429   2017-05-30    DEL         BOM 2017-06-01      1240    1   

  fare_choice      days  fare_choice_sc  dep_time_sc  
0        Deal  0.304110               1     0.270833  
1     Classic  0.013699               0     0.739583  
2       Saver  0.005479               3     0.375000  
3     Classic  0.005479               0     0.895833  
4     Classic  0.005479               0     0.527778

In [40]:
#select columns here for features
flightDataTestPd = test_df[['id','pax', 'days','dep_time_sc']]
flightDataTest = flightDataTestPd.as_matrix(columns=flightDataTestPd.columns[0:])

#change the length of the features based on the selection
data_X_testF = flightDataTest[:,0:featureLength]
#data_y_testF = flightDataTest[:,featureLength-1]
#print(data_y_test)
test_df.head()

id booking_date origin destination   dep_date  dep_time  pax  \
0  0.071429   2017-04-21    BLR         DEL 2017-06-24      1745    2   
1  0.285714   2017-05-24    BOM         DEL 2017-06-24      1700    2   
2  0.071429   2017-04-12    BLR         DEL 2017-06-24       700    1   
3  0.071429   2017-06-21    BLR         DEL 2017-06-24      1125    2   
4  0.214286   2017-05-31    BOM         CCU 2017-06-24      1905    1   

       days  dep_time_sc  
0  0.175342     0.739583  
1  0.084932     0.708333  
2  0.200000     0.291667  
3  0.008219     0.475694  
4  0.065753     0.795139

In [43]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.cross_validation import cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures
from sklearn import svm


data_X_train, data_X_test, data_y_train, data_y_test = train_test_split(X, y, test_size=0.3, random_state=42)


# Create linear regression object
regr = linear_model.LogisticRegression()
# Train the model using the training sets
regr.fit(data_X_train, data_y_train)


#regr = svm.SVC(kernel='linear', C = 1.0)
#regr.fit(data_X_train,data_y_train)

# predict class labels for the test set
predicted = regr.predict(data_X_test)
predicted_prob = regr.predict_proba(data_X_testF)
print(data_y_test)
print(predicted)


#print(regr.score(data_y_test,predicted))

idx = 0
df_y_pred = pd.DataFrame(predicted_prob)
df_y_pred.insert(loc=idx, column='id', value=np.nan)
df_y_pred['id'] = df_y_pred.index + 73831
print(df_y_pred.head(20))
prediction_location = r'prediction.csv'
df_y_pred.to_csv(prediction_location, index=False, header=['id', 'Classic', 'Deal', 'Flex', 'Saver'])

# The mean squared error
print("Mean absolute error: %.2f"
      % mean_absolute_error(data_y_test, predicted))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % r2_score(data_y_test, predicted))


#polynomial_features = PolynomialFeatures(degree=3, include_bias=False)

#pipeline = Pipeline([("polynomial_features", polynomial_features),("linear_regression", regr)])
#pipeline.fit(data_X_train, data_y_train)

    # Evaluate the models using crossvalidation
#scores = cross_val_score(pipeline, data_X_train, data_y_train, scoring="neg_mean_squared_error", cv=10)
#print(scores)

#pred_deg = pipeline.predict(data_X_test)
#print(pred_deg)
#print(data_y_test)

# The mean squared error
#print("Mean absolute error: %.2f"
#      % mean_absolute_error(data_y_test, pred_deg))
# Explained variance score: 1 is perfect prediction
#print('Variance score: %.2f' % r2_score(data_y_test, pred_deg))

#print(len(pred_deg))
#print(len(data_y_test))
#print(metrics.accuracy_score(data_y_test, pred_deg))
#print(metrics.confusion_matrix(data_y_test, pred_deg))

[ 3.  0.  3. ...,  0.  1.  1.]
[ 0.  0.  0. ...,  0.  1.  1.]
       id         0         1         2         3
0   73831  0.000298  0.766641  0.000344  0.232716
1   73832  0.039572  0.665555  0.011800  0.283072
2   73833  0.000099  0.772602  0.000116  0.227183
3   73834  0.593896  0.086880  0.072710  0.246513
4   73835  0.137490  0.485154  0.030964  0.346392
5   73836  0.114528  0.615598  0.016811  0.253063
6   73837  0.621684  0.067600  0.137572  0.173144
7   73838  0.618248  0.065902  0.105481  0.210369
8   73839  0.608750  0.081976  0.068339  0.240935
9   73840  0.346056  0.246793  0.065753  0.341398
10  73841  0.606419  0.094697  0.131410  0.167475
11  73842  0.618020  0.044403  0.111786  0.225791
12  73843  0.362222  0.237451  0.086622  0.313705
13  73844  0.628069  0.079226  0.081775  0.210931
14  73845  0.371674  0.230285  0.103392  0.294649
15  73846  0.131496  0.594739  0.047600  0.226164
16  73847  0.058895  0.674614  0.021725  0.244766
17  73848  0.625594  0.075880  0.08969

### Final test for submission

In [154]:
pipeline.fit(X, y)

# Make predictions using the testing set
data_y_pred = pipeline.predict(data_X_testF)
df_y_pred = pd.DataFrame(data_y_pred)
prediction_location = r'prediction.csv'
df_y_pred.to_csv(prediction_location, index=False, header=['AvgWtTime'])
prediction_location = r'train_mod.csv'
np.savetxt("train_mod.csv", flightData, delimiter=",")
# The coefficients
print('Coefficients: \n', regr.coef_)
# The mean squared error
#print("Mean squared error: %.2f"
#      % mean_squared_error(data_y_test, data_y_pred))
# Explained variance score: 1 is perfect prediction
#print('Variance score: %.2f' % r2_score(data_y_test, data_y_pred))

Coefficients: 
 [ -7.64530259e+00  -1.29502594e+00   2.14665581e-01  -2.91826937e+01
  -3.46828210e-01   2.22305555e+00  -4.83827052e-02  -5.44089625e-03
   1.66356177e+00   1.73914026e-02   9.69630244e-02  -1.32595301e-02
   1.72320568e+00   1.93442589e-01   3.84552808e-04  -1.44564484e-01
  -9.20029442e-03   1.33276125e+01   1.34698060e+00  -3.23458632e-02
  -1.83319994e-01  -1.83174282e-02  -6.44107336e-04   7.57756678e-02
   8.46564313e-03   9.36540718e-03   2.36708747e-04  -5.08547557e-02
  -6.61870677e-03  -8.42549411e-06   3.60231759e-03   1.67912415e-04
  -3.72282061e-01  -4.59669943e-02   2.93164663e-03  -1.93596081e-03
   1.96755893e-04  -2.25508813e-02  -8.22450170e-03  -1.14503013e-05
   3.97763056e-03   4.20073522e-04  -3.35132874e-01  -6.80967000e-02
   2.18342613e-03   1.14505587e-07  -7.29166959e-05  -4.13667626e-06
   1.53668232e-02   1.60319105e-03   3.90086178e-05  -1.06926744e+00
  -1.53161182e-01  -2.15356466e-03  -6.59889272e-04]


In [ ]:
print(data_X_test.shape)
#print(data_y_test.shape)

In [117]:
index = 138
df['Day'][index] = int(df['Date'][index].day)
print(type(df['Day'][index]))

print(type(df['Date'][index].dayofweek))

<class 'numpy.int64'>
<class 'int'>


/Users/eabraham/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app


In [64]:
flightDataTestPd.head(20)

Day Hour  Total  Flights  Booths
0     1    0    300        2      12
1     1    4    143        1       4
2     1    6    411        2      13
3     1    7    312        1      16
4     1    8    427        2      14
5     1    9    238        1      15
6     1   10    885        5      17
7     1   11    556        3      17
8     1   12    708        4      25
9     1   13   2469       11      33
10    1   14   2810       12      37
11    1   15   1829        8      27
12    1   16   1554        8      31
13    1   17   1384        9      30
14    1   18   2555       12      26
15    1   19   1021        5      21
16    1   20    410        2      11
17    1   21    259        1      10
18    1   23    471        3      10
19    2    0    321        2      10